import { Outfit } from "next/font/google";
import "./globals.css";
import { Weight } from "lucide-react";

const outfit = Outfit({ subsets: ["latin"], Weight: ["400", "500", "600", "700"] });

export const metadata = {
  title: "Full Stack Next Blogging App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
